version: '3'
services:
  api:
    build:
      context: ./api
    container_name: mtl-server
    image: lovelgeorge/realestate_backend
    ports:
      - "3000:3000"
   

  client:
    build:
      context: ./client
    container_name: mtl-client
    image: lovelgeorge/realestate_frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
      - socket

  socket:
    build:
      context: ./socket
    container_name: mtl-socket
    image: lovelgeorge/realestate_socket
    ports:
      - "8800:8800"
